Repository jiant-dev/jiant, pull requests merged in 2020-08, with the labels that each got.

#136 Add README.md for glue submission formatter script
  jiant/scripts/postproc/README.md
Labels: documentation

#137 Add direct data download support for WSC, MultiRC, and ReCoRD
  jiant/scripts/download_data/constants.py
  jiant/scripts/download_data/datasets/files_tasks.py
  jiant/scripts/download_data/runscript.py
  jiant/utils/python/filesystem.py
Labels: bug

#146 Fix for failing WSC tokenization on test set
  jiant/tasks/lib/wsc.py
Labels: bug

#153 Fix WiC tokenization using adjacency matrix alignment utility
  jiant/tasks/lib/wic.py
  jiant/utils/testing/utils.py
  jiant/utils/tokenization_normalization.py
  tests/tasks/lib/test_wic.py
Labels: bug

#145 Add SuperGLUE prediction writing methods to SuperGLUE tasks
  jiant/scripts/download_data/datasets/nlp_tasks.py
  jiant/tasks/core.py
  jiant/tasks/lib/boolq.py
  jiant/tasks/lib/commitmentbank.py
  jiant/tasks/lib/copa.py
  jiant/tasks/lib/multirc.py
  jiant/tasks/lib/record.py
  jiant/tasks/lib/rte.py
  jiant/tasks/lib/wic.py
  jiant/tasks/lib/wsc.py
Labels: enhancement

#142 Add SUPERGLUE benchmark formatter
  jiant/scripts/postproc/benchmark_submission_formatter.py
  jiant/scripts/postproc/benchmarks.py
  jiant/scripts/postproc/glue_submission_formatter.py
  jiant/tasks/constants.py
Labels: enhancement

#141 XTREME Eval script.
  examples/guides/task_specific.md
  jiant/proj/main/runner.py
  jiant/scripts/download_data/datasets/xtreme.py
  jiant/scripts/postproc/README.md
  jiant/scripts/postproc/__init__.py
  jiant/scripts/postproc/glue/README.md
  jiant/scripts/postproc/glue/__init__.py
  jiant/scripts/postproc/xtreme/README.md
  jiant/scripts/postproc/xtreme/subscripts/a_download_model.sh
  jiant/scripts/postproc/xtreme/subscripts/b_download_data.sh
  jiant/scripts/postproc/xtreme/subscripts/c_tokenize_and_cache.sh
  jiant/scripts/postproc/xtreme/subscripts/d_write_configs.sh
  jiant/scripts/postproc/xtreme/subscripts/e_run_models.sh
  jiant/scripts/postproc/xtreme/subscripts/run_all.sh
  jiant/scripts/postproc/xtreme/xtreme_runconfig_writer.py
  jiant/scripts/postproc/xtreme/xtreme_submission.py
  jiant/tasks/evaluate/core.py
  jiant/utils/transformer_utils.py
Labels: enhancement
