Repository jiant-dev/jiant, pull requests merged in 2020-06, with the labels that each got.

#27 Add docs for model code
  jiant/proj/main/modeling/model_setup.py
  jiant/proj/main/modeling/primary.py
  jiant/proj/main/modeling/taskmodels.py
  jiant/shared/model_resolution.py
  jiant/shared/model_setup.py
Labels: documentation

#34 Add test for SST task data preprocessing
  tests/tasks/lib/resources/data/sst/test.jsonl
  tests/tasks/lib/resources/data/sst/train.jsonl
  tests/tasks/lib/resources/data/sst/val.jsonl
  tests/tasks/lib/resources/sst.json
  tests/tasks/lib/test_sst.py
Labels: test

#35 featurization test for mnli
  jiant/tasks/lib/mnli.py
  tests/tasks/lib/resources/data/mnli/mnli_test.jsonl
  tests/tasks/lib/resources/data/mnli/mnli_train.jsonl
  tests/tasks/lib/resources/data/mnli/mnli_val.jsonl
  tests/tasks/lib/resources/mnli.json
  tests/tasks/lib/test_mnli.py
Labels: test

#32 Adding non-XTREME tasks
  examples/simple_runner.py
  jiant/proj/main/modeling/model_setup.py
  jiant/proj/main/runscript.py
  jiant/proj/simple/preprocessing.py
  jiant/shared/model_resolution.py
  jiant/tasks/evaluate/core.py
  jiant/tasks/lib/abductive_nli.py
  jiant/tasks/lib/adversarial_nli.py
  jiant/tasks/lib/boolq.py
  jiant/tasks/lib/ccg.py
  jiant/tasks/lib/commitmentbank.py
  jiant/tasks/lib/commonsenseqa.py
  jiant/tasks/lib/copa.py
  jiant/tasks/lib/cosmosqa.py
  jiant/tasks/lib/hellaswag.py
  jiant/tasks/lib/mlm_crosslingual_wiki.py
  jiant/tasks/lib/mlm_wikitext_103.py
  jiant/tasks/lib/multirc.py
  jiant/tasks/lib/record.py
  jiant/tasks/lib/scitail.py
  jiant/tasks/lib/socialiqa.py
  jiant/tasks/lib/squad.py
  jiant/tasks/lib/swag.py
  jiant/tasks/lib/templates/__init__.py
  jiant/tasks/lib/templates/hacky_tokenization_matching.py
  jiant/tasks/lib/templates/mlm.py
  jiant/tasks/lib/templates/multiple_choice.py
  jiant/tasks/lib/templates/squad_style/__init__.py
  jiant/tasks/lib/templates/squad_style/core.py
  jiant/tasks/lib/templates/squad_style/utils.py
  jiant/tasks/lib/wic.py
  jiant/tasks/lib/wsc.py
  jiant/tasks/retrieval.py
  jiant/tasks/utils.py
  jiant/utils/python/io.py
  requirements.txt
Labels: enhancement

#74 Added getter for ccg test examples
  jiant/tasks/lib/ccg.py
Labels: bug

#75 Fixed SocialIQA MC labels in socialiqa.py
  jiant/tasks/lib/socialiqa.py
Labels: bug

#84 Fixes for task MultiRC tokenize_and_cache.py. Fixes #76.
  jiant/tasks/evaluate/core.py
  requirements.txt
Labels: bug

#82 Add some basic docs/tests for truncate_sequences
  jiant/tasks/utils.py
  tests/utils/test_utils.py
Labels: documentation, test

#80 Add core sequence alignment functionality from jiant1
  jiant/utils/retokenize.py
  requirements.txt
  tests/utils/test_token_alignment.py
Labels: enhancement

#81 Add first edge probing task example (SPR1)
  jiant/proj/main/modeling/model_setup.py
  jiant/proj/main/modeling/taskmodels.py
  jiant/tasks/core.py
  jiant/tasks/evaluate/core.py
  jiant/tasks/lib/spr1.py
  jiant/tasks/lib/templates/edge_probing.py
  jiant/tasks/retrieval.py
  tests/tasks/lib/resources/data/spr1/test.jsonl
  tests/tasks/lib/resources/data/spr1/train.jsonl
  tests/tasks/lib/resources/spr1.json
  tests/tasks/lib/test_spr1.py
Labels: task
